<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'PhenomCLinter' => 'lib/PhenomCLinter.php',
    'PhenomCallgrindFile' => 'lib/cov/PhenomCallgrindFile.php',
    'PhenomDwarfLineInfo' => 'lib/cov/PhenomDwarfLineInfo.php',
    'PhenomLicenseLinter' => 'lib/PhenomLicenseLinter.php',
    'PhenomLintEngine' => 'lib/PhenomLintEngine.php',
    'PhenomUnitEngine' => 'lib/PhenomUnitEngine.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'PhenomCLinter' => 'ArcanistLinter',
    'PhenomLicenseLinter' => 'ArcanistLicenseLinter',
    'PhenomLintEngine' => 'ArcanistLintEngine',
    'PhenomUnitEngine' => 'ArcanistBaseUnitTestEngine',
  ),
));
